name: tekaly_chordpro
description: Dart chord pro format/parser
version: 0.1.3
publish_to: none

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  path: ">=1.9.1"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
    version: '>=0.15.2'
  tekaly_music_note:
    git:
      url: https://github.com/tekartikprj/music
      path: packages/music_note
    version: '>=0.1.0'
dev_dependencies:
  lints: ">=6.0.0"
  test: ">=1.26.3"

resolution: workspace
