name: tekaly_music_note
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  collection: ">=1.19.1"

dev_dependencies:
  lints: ">=6.0.0"
  test: ">=1.26.3"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      path: packages/lints
    version: '>=0.1.0'
resolution: workspace
